config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :stocks
  get 'welcome/home'
  devise_for :users
  root to: "welcome#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stock.rb
class Stock < ApplicationRecord
  validates_presence_of :name, :interest, :duration, :unit_price
  validates_numericality_of :interest, :unit_price, greater_than: 0
  validates_numericality_of :duration, greater_than_or_equal_to: 1

  belongs_to :user
  monetize :unit_price_cents

  def year_value(year)
    (unit_price_dollars * (1 + interest_decimal) ** year).round(2)
  end

  def unit_price_dollars
    unit_price_cents / 100
  end

  def interest_decimal
    interest.to_d / 100
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :stocks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  rescue_from ActiveRecord::RecordNotFound do
    head :not_found
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_stock, only: %i[show edit update destroy]

  # GET /stocks
  # GET /stocks.json
  def index
    @stocks = current_user.stocks
  end

  # GET /stocks/1
  # GET /stocks/1.json
  def show
    @chart_data = (1..@stock.duration).inject({}) do |result, year|
      result.merge(year => @stock.year_value(year))
    end
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit;
  end

  # POST /stocks
  # POST /stocks.json
  def create
    @stock = current_user.stocks.new(stock_params)
    respond_to do |format|
      if @stock.save
        format.html {redirect_to root_path, notice: 'Stock was successfully created.'}
        format.json {render :show, status: :created, location: @stock}
      else
        format.html {render :new}
        format.json {render json: @stock.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /stocks/1
  # PATCH/PUT /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html {redirect_to @stock, notice: 'Stock was successfully updated.'}
        format.json {render :show, status: :ok, location: @stock}
      else
        format.html {render :edit}
        format.json {render json: @stock.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /stocks/1
  # DELETE /stocks/1.json
  def destroy
    @stock.destroy
    respond_to do |format|
      format.html {redirect_to stocks_url, notice: 'Stock was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_stock
    @stock = current_user.stocks.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def stock_params
    params.require(:stock).permit(:name, :unit_price, :interest, :duration)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
    redirect_to stocks_path unless current_user.nil?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/welcome_controller_helper.rb
module WelcomeControllerHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |name, msg| %>
  <%= content_tag :div, class: "alert alert-#{ name == "alert" ? "danger" : "success" } alert-dismissable", role: "alert" do %>
    <button type="button" class="close" data-dismiss="alert">
      <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <%= msg %>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<% content_for :not_authorized do %>
  <ul class="nav navbar-nav mr-auto"></ul>
  <ul class="nav navbar-nav">
    <li><%= link_to 'Sign In', new_user_session_path %></li>
  </ul>
<% end %>
<% content_for :authorized do %>
  <ul class="nav navbar-nav mr-auto">
    <li class="nav-item"><%= link_to 'Add Stock', new_stock_path %></li>
    <li class="nav-item"><%= link_to "Stocks", stocks_path %></li>
  </ul>
  <ul class="nav navbar-nav">
    <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Stock calculator</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Stock calculator", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="collapse navbar-collapse justify-content-between">
      <%= render partial: 'layouts/navigation' %>
      <%= current_user.nil? ? yield(:not_authorized) : yield(:authorized) %>
    </div>
  </div>
</nav>
<div class="container">
  <%= render partial: 'layouts/flash' %>
  <%= yield %>
</div>
</body>
</html>

app/views/stocks/_form.html.erb
<%= form_for(@stock, html: {class: "form-horizontal", role: "form"}) do |f| %>
  <% if @stock.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@stock.errors.count, "error") %> prohibited this stock from being saved:</h4>

      <ul>
        <% @stock.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control", required: true %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :unit_price, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :unit_price, class: "form-control", min: "0" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :interest, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :interest, class: "form-control", min: "0" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :duration, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :duration, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/stocks/edit.html.erb
<div class="page-header">
  <%= link_to stocks_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @stock, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing stock</h1>
</div>

<%= render 'form' %>

app/views/stocks/index.html.erb
<div class="page-header">
  <%= link_to new_stock_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Stock
  <% end %>
  <h1>Listing stocks</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
    <tr>
      <th>Name</th>
      <th>Unit price</th>
      <th>Interest</th>
      <th>Duration</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
    </thead>

    <tbody>
    <% if @stocks.size > 0 %>
      <% @stocks.each do |stock| %>
        <tr>
          <td><%= link_to stock.name, stock %></td>
          <td><%= humanized_money_with_symbol stock.unit_price %></td>
          <td><%= stock.interest %></td>
          <td><%= stock.duration %></td>
          <td><%= link_to 'Show', stock %></td>
          <td><%= link_to 'Edit', edit_stock_path(stock) %></td>
          <td><%= link_to 'Destroy', stock, method: :delete, data: {confirm: 'Are you sure?'} %></td>
        </tr>
      <% end %>
    <% else %>
      <tr>
        <td class="text-center" colspan="7">No data yet...</td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/stocks/new.html.erb
<div class="page-header">
  <%= link_to stocks_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New stock</h1>
</div>

<%= render 'form' %>

app/views/stocks/show.html.erb
<div class="page-header">
  <%= link_to stocks_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_stock_path(@stock), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show stock</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @stock.name %></dd>

  <dt>Unit price:</dt>
  <dd><%= humanized_money_with_symbol @stock.unit_price %></dd>

  <dt>Interest:</dt>
  <dd><%= @stock.interest %></dd>

  <dt>Duration:</dt>
  <dd><%= @stock.duration %></dd>
</dl>

<%= column_chart @chart_data, xtitle: "Years", ytitle: "Amount, dollars" %>

app/views/welcome/home.html.erb
<div class="page-header">
  <h1>Stock productivity calculator</h1>
</div>